server:
  port: ${PORT:8000}

spring:
  main:
    banner-mode: "OFF"  # Deshabilita el banner de Spring Boot

# Discovery Server Access
eureka:
  instance:
    preferIpAddress: false

kafka:
  product:
    topic: "pub-create-product"
    groupId: "product-consumer"
  acks: "all"
  retries: 0
  batch:
    size: "1000000"
  linger:
    ms: "500"