server:
  port: ${PORT:8761}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    cabanas.garcia.ismael: 'DEBUG'

security:
  user:
    password: ${eureka.password} # Don't use a default password in a real app

eureka:
  client: # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  password: ${SECURITY_USER_PASSWORD:password}

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf